apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: email-summarizer
  labels:
    app: api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: ${ECR_REPOSITORY_URL}/email-summarizer-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: VECTOR_SERVICE_URL
          value: "http://vector-service:8001"
        - name: ML_SERVICE_URL
          value: "http://ml-service:8002"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: openai-api-key
        - name: HUBSPOT_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: hubspot-api-key
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: email-summarizer
spec:
  selector:
    app: api-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
