apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-service
  namespace: email-summarizer
  labels:
    app: vector-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-service
  template:
    metadata:
      labels:
        app: vector-service
    spec:
      containers:
      - name: vector-service
        image: ${ECR_REPOSITORY_URL}/email-summarizer-vector:latest
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: vector-secrets
              key: openai-api-key
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: vector-secrets
              key: pinecone-api-key
        - name: PINECONE_ENVIRONMENT
          value: "us-west1-gcp"
        - name: PINECONE_INDEX
          value: "email-summarizer"
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vector-service
  namespace: email-summarizer
spec:
  selector:
    app: vector-service
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
